branch-defaults:
  default:
    environment: drew-app-server-prod
global:
  application_name: drew-app-server
  branch: null
  default_ec2_keyname: drew-app
  default_platform: Ruby 2.6 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
