branch-defaults:
  default:
    environment: drew-server-prod
    group_suffix: null
global:
  application_name: drew-server
  branch: null
  default_ec2_keyname: drew-app
  default_platform: Ruby 2.5 (Puma)
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
